version: "3"
services:
    docker:
        image: docker:dind
        environment:
            DOCKER_TLS_CERTDIR: /certs
        ports:
            - "2376:2376"
        privileged: true
        volumes:
            - "jenkins-docker-certs:/certs/client"
            - "jenkins-data:/var/jenkins_home"
    jenkins-blueocean:
        image: jenkinsci/blueocean
        environment:
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - "jenkins-data:/var/jenkins_home"
            - "jenkins-docker-certs:/certs/client:ro"
volumes:
    jenkins-data:
    jenkins-docker-certs: