name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Build the C# code
      run: dotnet build
    
    - name: Run the C# tests
      run: dotnet test

    - name: Install Typescript dependencies and build Typescript code
      run: cd DotnetTemplate.Web && npm install && npm run build
    
    - name: Typescript linting and tests
      run: cd DotnetTemplate.Web && npm run lint && npm t

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN  }}

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: robinleach/dotnettemplate:latest