name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build the C# code
      run: dotnet build
    
    - name: Run the C# tests
      run: dotnet test

    - name: Install Typescript dependencies and build Typescript code
      run: cd DotnetTemplate.Web && npm install && npm run build
    
    - name: Typescript linting and tests
      run: cd DotnetTemplate.Web && npm run lint && npm t

  docker-publish:
    name: Publish the image to Docker
    needs: [build]
    runs-on: ubuntu-latest  
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN  }}

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: robinleach/dotnettemplate:latest

  heroku-deploy:
    name: Deploy to Heroku
    needs: [build, docker-publish]
    runs-on: ubuntu-latest  
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Publish to Heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "module-8"
        heroku_email: "robin.leach@softwire.com"
        usedocker: true